/* Write your PL/SQL query statement below */

SELECT EMPLOYEE_ID AS "employee_id" FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL AND SALARY <30000 AND MANAGER_ID  NOT IN (SELECT EMPLOYEE_ID FROM EMPLOYEES) ORDER BY EMPLOYEE_ID;
