/* Write your PL/SQL query statement below */

-- SELECT * FROM STUDENTS S FULL OUTER JOIN EXAMINATIONS E ON S.STUDENT_ID = E.STUDENT_ID;

SELECT T.STUDENT_ID AS "student_id",T.STUDENT_NAME AS "student_name",T.SUBJECT_NAME AS "subject_name",COUNT(E.SUBJECT_NAME) as "attended_exams" FROM (SELECT * FROM STUDENTS S CROSS JOIN SUBJECTS U ORDER BY STUDENT_ID) T LEFT JOIN EXAMINATIONS E ON T.STUDENT_ID = E.STUDENT_ID AND T.SUBJECT_NAME = E.SUBJECT_NAME GROUP BY T.STUDENT_ID, T.STUDENT_NAME,T.SUBJECT_NAME ORDER BY T.STUDENT_ID ; 