/* Write your PL/SQL query statement below */
-- P.PROJECT_ID, AVG(SUM(E.EXPERIENCE_YEARS))
SELECT P.PROJECT_ID,ROUND(SUM(E.EXPERIENCE_YEARS)/COUNT(P.PROJECT_ID),2) "average_years" FROM PROJECT P LEFT JOIN EMPLOYEE E ON P.EMPLOYEE_ID = E.EMPLOYEE_ID GROUP BY P.PROJECT_ID;
