/* Write your PL/SQL query statement below */


SELECT ROUND(SUM(TIV_2016),2)  AS "tiv_2016"FROM INSURANCE I 
JOIN
(SELECT TIV_2015 FROM INSURANCE GROUP BY TIV_2015 HAVING COUNT(DISTINCT PID)>1) T
ON I.TIV_2015 = T.TIV_2015
JOIN
(SELECT CONCAT(LAT,LON) AS LAT_LON FROM INSURANCE GROUP BY CONCAT(LAT,LON) HAVING COUNT(DISTINCT PID) = 1)X
ON  CONCAT(I.LAT,I.LON) = X.LAT_LON;