/* Write your PL/SQL query statement below */

SELECT A.MACHINE_ID,ROUND(AVG(T.TIMESTAMP-A.TIMESTAMP),3) AS processing_time FROM ACTIVITY A, ACTIVITY T WHERE A.MACHINE_ID = T.MACHINE_ID AND A.PROCESS_ID = T.PROCESS_ID AND A.TIMESTAMP<T.TIMESTAMP GROUP BY A.MACHINE_ID;
