/* Write your PL/SQL query statement below */

SELECT PRODUCT_NAME "product_name", UNIT AS "UNIT" FROM( SELECT P.PRODUCT_ID "PRODUCT_ID", SUM(UNIT) AS "UNIT" FROM PRODUCTS P JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID  WHERE O.ORDER_DATE BETWEEN '2020-02-01' AND '2020-02-29' GROUP BY P.PRODUCT_ID) T, PRODUCTS P WHERE T.PRODUCT_ID = P.PRODUCT_ID  AND UNIT >=100 ;
