/* Write your PL/SQL query statement below */

SELECT TO_CHAR(SELL_DATE,'YYYY-MM-DD') "sell_date", 
COUNT(DISTINCT(PRODUCT)) "num_sold", 
LISTAGG(PRODUCT,',') WITHIN GROUP (ORDER BY PRODUCT)  "products"
FROM (SELECT DISTINCT * FROM ACTIVITIES) GROUP BY SELL_DATE ORDER BY SELL_DATE;


