/* Write your PL/SQL query statement below */

SELECT PRODUCT_ID, 10 AS "PRICE" FROM PRODUCTS  WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM PRODUCTS WHERE CHANGE_DATE <= '2019-08-16') 
UNION 
SELECT PRODUCT_ID, NEW_PRICE AS "PRICE" FROM PRODUCTS WHERE (PRODUCT_ID,COALESCE(CHANGE_DATE,TO_DATE('2019-08-16','YYYY-MM-DD')) )IN (SELECT PRODUCT_ID, COALESCE(MAX(CHANGE_DATE),TO_DATE('2019-08-16','YYYY-MM-DD')) FROM PRODUCTS WHERE CHANGE_DATE < = '2019-08-16' GROUP BY PRODUCT_ID);

-- SELECT PRODUCT_ID, COALESCE(MIN(CHANGE_DATE),TO_DATE('2019-08-16','YYYY-MM-DD')) FROM PRODUCTS WHERE  GROUP BY PRODUCT_ID;