/* Write your PL/SQL query statement below */


SELECT R.CONTEST_ID,ROUND(COUNT(U.USER_ID)/ (SELECT COUNT(T.USER_ID) FROM USERS T) * 100,2) AS "percentage"FROM USERS U RIGHT JOIN REGISTER R ON U.USER_ID = R.USER_ID GROUP BY R.CONTEST_ID ORDER BY "percentage" desc,R.CONTEST_ID;
