SELECT PRODUCT_ID,YEAR AS "first_year",QUANTITY,PRICE FROM (SELECT S.PRODUCT_ID,S.YEAR ,S.QUANTITY,S.PRICE, DENSE_RANK() OVER(PARTITION BY S.PRODUCT_ID ORDER BY S.YEAR) AS "RANK" FROM SALES S, PRODUCT P WHERE S.PRODUCT_ID =  P.PRODUCT_ID) T  WHERE T.RANK =1  ;  

/* Write your PL/SQL query statement below */
-- THIS IS A BETTER SOLUTION AS WE DO NOT REQUIRE TO CALL DENSE_RANK() FUNCTION OR RANK FUNCTION SIMPLE ORACLE FUNCTION CALL.

SELECT S.PRODUCT_ID, S.YEAR AS "first_year", S.QUANTITY,S.PRICE FROM SALES S WHERE (S.PRODUCT_ID, S.YEAR) IN (SELECT T.PRODUCT_ID,MIN(T.YEAR) AS YEAR FROM SALES T GROUP BY T.PRODUCT_ID);
