/* Write your PL/SQL query statement below */


SELECT E.EMPLOYEE_ID, E.DEPARTMENT_ID FROM EMPLOYEE E WHERE E.PRIMARY_FLAG = 'Y';
UNION
SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM EMPLOYEE  WHERE EMPLOYEE_ID IN ( SELECT EMPLOYEE_ID FROM EMPLOYEE GROUP BY EMPLOYEE_ID HAVING COUNT(EMPLOYEE_ID) =1);

